Notes 관련 API 개발
prolog-project/prolog-project-backend pull request #26
Opened 2024-03-03 05:28 UTC by KimGwangJe

아래 내용을 중점으로 리뷰 부탁드립니다!

1. Image 엔티티를 우선 Notes 부분에 넣어놨는데 다른 곳에 빼는게 나을까요?
2. JWT 관련 코드에서 사용자의 ID가 아닌 Email을 넣는 것 같아 JwtProvider에서 이메일을 뽑아서 사용하는 코드로 변경하였는데 다르다면 말씀해 주세요!
3. 메서드 명 또는 변수 명이 이상하거나 틀린 부분은 말씀해 주세요

2024-03-03 10:57 UTC, Choi-Young-Eun commented on src/main/java/com/prolog/prologbackend/Project/Controller/ProjectController.java
> +        String token = jwtProvider.substringToken(request.getHeader("ACCESS_TOKEN"));
이 작업은 권한이 필요한 요청의 경우 인가 필터에서 진행하는 작업입니다
컨트롤러 내 메서드에서 매개변수로 @AuthenticationPrincipal Member member 받아서 사용하시면 되세요!

2024-03-03 11:05 UTC, Choi-Young-Eun commented on src/main/java/com/prolog/prologbackend/Notes/Domain/Image.java
이미지 엔티티는 공통으로 뺄까요? 아님 도메인별 이미지 엔티티를 생성하는 게 좋을까요?

2024-03-03 11:15 UTC, Choi-Young-Eun commented on src/main/java/com/prolog/prologbackend/Exception/GlobalExceptionHandler.java
> +            if (t.getTargetType().isAssignableFrom(NotesType.class)) {
광제님 제가 앞전에 추가한 코드는 어디 있을까요..?
GlobalExceptionHandler에서는 특정 케이스에 국한되는 예외 처리 보다 범용적으로 사용할 수 있도록 해야 될 것 같아요..!
동적으로 진행하지 않고 케이스별로 나눠서 직접적인 ExceptionType을 사용하여 에러 메시지를 구성한다면 코드가 불필요하게 길어지고 보기 좋지 않을 것 같습니다.

2024-03-03 11:17 UTC, Choi-Young-Eun requested changes
확인 부탁드립니다!

2024-03-04 04:26 UTC, KimGwangJe commented on src/main/java/com/prolog/prologbackend/Notes/Domain/Image.java
회원 같은 경우에는 테이블에 프로필 이미지, 파일명이라는 속성이 있어서 따로 이미지 테이블과 관계를 맺지 않아도 될 것 같고 프로젝트 스택 같은 경우에는 한 번 추가하면 수정할 일이 많지 않아 지금 있는 이미지 테이블을 일지에 대한 이미지 테이블로 사용하여도 괜찮을 것 같아요!

2024-03-04 05:36 UTC, closed without merging